import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'fr', 'ar', 'nl', 'de', 'es'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? frText = '',
    String? arText = '',
    String? nlText = '',
    String? deText = '',
    String? esText = '',
  }) =>
      [enText, frText, arText, nlText, deText, esText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // DriverProfile
  {
    '7u4l7vgq': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'nl': 'Bewerk profiel',
    },
    '4vudjo57': {
      'en': 'My posts',
      'ar': 'مشاركاتي',
      'de': 'Meine Posts',
      'es': 'Mis publicaciones',
      'fr': 'Mes publications',
      'nl': 'Mijn posts',
    },
    '9v52kv29': {
      'en': 'Notification Settings',
      'ar': 'إعدادات الإشعار',
      'de': 'Benachrichtigungseinstellungen',
      'es': 'Configuración de las notificaciones',
      'fr': 'Paramètres de notification',
      'nl': 'Notificatie instellingen',
    },
    'ihb9f55w': {
      'en': 'Account Information',
      'ar': 'معلومات الحساب',
      'de': 'Kontoinformationen',
      'es': 'Información de la cuenta',
      'fr': 'Information sur le compte',
      'nl': 'Account Informatie',
    },
    'fpgfkmbs': {
      'en': 'Phone Number',
      'ar': 'رقم التليفون',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'nl': 'Telefoonnummer',
    },
    'z95jycqg': {
      'en': 'Address',
      'ar': 'عنوان',
      'de': 'Adresse',
      'es': 'DIRECCIÓN',
      'fr': 'Adresse',
      'nl': 'Adres',
    },
    '2lhkgqj7': {
      'en': 'Vehicle Information',
      'ar': 'معلومات السيارة',
      'de': 'Fahrzeuginformationen',
      'es': 'Información del vehículo',
      'fr': 'Informations sur le véhicule',
      'nl': 'Voertuig informatie',
    },
    'xlflvprr': {
      'en': 'Vehicle Type',
      'ar': 'نوع السيارة',
      'de': 'Fahrzeugtyp',
      'es': 'tipo de vehiculo',
      'fr': 'Type de véhicule',
      'nl': 'Voertuigtype',
    },
    '98x5qegb': {
      'en': 'License Plate    ',
      'ar': 'لوحة الترخيص',
      'de': 'Nummernschild',
      'es': 'Placa',
      'fr': 'Plaque d\'immatriculation',
      'nl': 'Nummerplaat',
    },
    'ewt52bqi': {
      'en': 'Bank Account Information',
      'ar': 'معلومات الحساب المصرفي',
      'de': 'Bankkonto Information',
      'es': 'Información de cuenta bancaria',
      'fr': 'Information de compte bancaire',
      'nl': 'Bankrekeninginformatie',
    },
    'm7dvo3b3': {
      'en': 'Bank Name',
      'ar': 'اسم البنك',
      'de': 'Bank Name',
      'es': 'Nombre del banco',
      'fr': 'Nom de banque',
      'nl': 'Banknaam',
    },
    'hl3azp60': {
      'en': 'Account Number',
      'ar': 'رقم حساب',
      'de': 'Accountnummer',
      'es': 'Número de cuenta',
      'fr': 'Numéro de compte',
      'nl': 'Rekeningnummer',
    },
    'sjp89o35': {
      'en': 'Log Out',
      'ar': 'تسجيل خروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'nl': 'Uitloggen',
    },
    '1wa9kgiu': {
      'en': 'Delete my account ',
      'ar': 'احذف حسابي',
      'de': 'Mein Konto löschen',
      'es': 'Borrar mi cuenta',
      'fr': 'Supprimer mon compte',
      'nl': 'Verwijder mijn account',
    },
    'x6b95u9c': {
      'en': 'Profile',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'nl': 'Profiel',
    },
  },
  // resetPassWord1
  {
    'ic2lei9t': {
      'en': 'CargoMeet',
      'ar': 'كارجو كونيكت',
      'de': 'CargoConnect',
      'es': 'CargoConnect',
      'fr': 'CargoConnect',
      'nl': 'CargoConnect',
    },
    'j1dq0s3f': {
      'en': 'Reset Password',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'fr': 'réinitialiser le mot de passe',
      'nl': 'Wachtwoord opnieuw instellen',
    },
    'xsq9u9j2': {
      'en': 'Enter your email address below to reset your password.',
      'ar':
          'أدخل عنوان بريدك الإلكتروني أدناه لإعادة تعيين كلمة المرور الخاصة بك.',
      'de':
          'Geben Sie unten Ihre E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen.',
      'es':
          'Ingrese su dirección de correo electrónico a continuación para restablecer su contraseña.',
      'fr':
          'Entrez votre adresse e-mail ci-dessous pour réinitialiser votre mot de passe.',
      'nl':
          'Vul hieronder uw e-mailadres in om uw wachtwoord opnieuw in te stellen.',
    },
    'oj6zfzav': {
      'en': 'Email',
      'ar': 'بريد إلكتروني',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'nl': 'E-mail',
    },
    '7jykax27': {
      'en': 'Reset Password',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'fr': 'réinitialiser le mot de passe',
      'nl': 'Wachtwoord opnieuw instellen',
    },
    'ty4p0eij': {
      'en': 'Remember your password? ',
      'ar': 'تذكر كلمة المرور الخاصة بك؟',
      'de': 'Erinnern Sie sich an Ihr Passwort?',
      'es': '¿Recuerdas tu contraseña?',
      'fr': 'Vous vous souvenez de votre mot de passe ?',
      'nl': 'Onthoud uw wachtwoord?',
    },
    'qw41aag9': {
      'en': 'Sign In',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'nl': 'Aanmelden',
    },
    '3frrj4fu': {
      'en': 'Password reset',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecimiento de contraseña',
      'fr': 'Réinitialisation du mot de passe',
      'nl': 'Wachtwoord reset',
    },
  },
  // HomePage
  {
    'tnjivtp9': {
      'en': 'Endless route options',
      'ar': 'خيارات الطريق التي لا نهاية لها',
      'de': 'Endlose Routenoptionen',
      'es': 'Opciones de ruta infinitas',
      'fr': 'Options d\'itinéraire infinies',
      'nl': 'Eindeloze routemogelijkheden',
    },
    'j2q364xy': {
      'en': 'Departure    ',
      'ar': 'رحيل',
      'de': 'Abfahrt',
      'es': 'Partida',
      'fr': 'Départ',
      'nl': 'Vertrek',
    },
    'qwb39ptm': {
      'en': 'Destination',
      'ar': 'وجهة',
      'de': 'Ziel',
      'es': 'Destino',
      'fr': 'Destination',
      'nl': 'Bestemming',
    },
    '1b8owjsk': {
      'en': 'Find',
      'ar': 'يجد',
      'de': 'Finden',
      'es': 'Encontrar',
      'fr': 'Trouver',
      'nl': 'Vinden',
    },
    '7e3ms7sr': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // MessagesList
  {
    'vxho32px': {
      'en': 'Messages',
      'ar': 'رسائل',
      'de': 'Mitteilungen',
      'es': 'Mensajes',
      'fr': 'messages',
      'nl': 'Berichten',
    },
    'nvpevsrk': {
      'en': 'Saveds',
      'ar': 'المحفوظة',
      'de': 'Gespeichert',
      'es': 'Guardados',
      'fr': 'Enregistrés',
      'nl': 'Opgeslagen',
    },
  },
  // NewPassWord
  {
    'bp2uhx64': {
      'en': 'Reset Password',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'fr': 'réinitialiser le mot de passe',
      'nl': 'Wachtwoord opnieuw instellen',
    },
    'ci4zevx0': {
      'en': 'Enter your new password below.',
      'ar': 'أدخل كلمة المرور الجديدة أدناه.',
      'de': 'Geben Sie Ihr neues Passwort ein.',
      'es': 'Ingrese su nueva contraseña abajo.',
      'fr': 'Entrez votre nouveau mot de passe ci-dessous.',
      'nl': 'Voer je nieuw wachtwoord hieronder in.',
    },
    'rt30lfcc': {
      'en': 'New Password',
      'ar': 'كلمة المرور الجديدة',
      'de': 'Neues Kennwort',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'nl': 'nieuw paswoord',
    },
    'tnecnp6e': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'nl': 'bevestig wachtwoord',
    },
    'jn1bki5f': {
      'en': 'Reset Password',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'fr': 'réinitialiser le mot de passe',
      'nl': 'Wachtwoord opnieuw instellen',
    },
    'rx70xr7o': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'nl': 'Annuleren',
    },
  },
  // listDriverPostPage
  {
    'lcim7lkq': {
      'en': 'Departure',
      'ar': 'رحيل',
      'de': 'Abfahrt',
      'es': 'Partida',
      'fr': 'Départ',
      'nl': 'Vertrek',
    },
    '2h2mie5i': {
      'en': 'Destination',
      'ar': 'الوصول',
      'de': 'Ankunft',
      'es': 'Llegada',
      'fr': 'Arrivée',
      'nl': 'Aankomst',
    },
    'ibd3mlzw': {
      'en': '5',
      'ar': '5',
      'de': '5',
      'es': '5',
      'fr': '5',
      'nl': '5',
    },
    'j9tgjx82': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // Authentication
  {
    'vtjg5d6s': {
      'en': 'CargoMeet',
      'ar': 'كارجو كونيكت',
      'de': 'CargoConnect',
      'es': 'CargoConnect',
      'fr': 'CargoConnect',
      'nl': 'CargoConnect',
    },
    'wa1ra68j': {
      'en': 'Sign In',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'nl': 'Aanmelden',
    },
    'ld5nzc2j': {
      'en': 'Email Address',
      'ar': 'عنوان البريد الإلكتروني',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'nl': 'E-mailadres',
    },
    'hws66gj7': {
      'en': '@gmail.com',
      'ar': '@gmail.com',
      'de': '@gmail.com',
      'es': '@gmail.com',
      'fr': '@gmail.com',
      'nl': '@gmail.com',
    },
    'zlaxgudr': {
      'en': '@outlook.com',
      'ar': '@outlook.com',
      'de': '@outlook.com',
      'es': '@perspectiva.com',
      'fr': '@outlook.com',
      'nl': '@outlook.com',
    },
    'w6bua1mv': {
      'en': '@outlook.fr',
      'ar': '@outlook.fr',
      'de': '@outlook.fr',
      'es': '@outlook.es',
      'fr': '@outlook.fr',
      'nl': '@outlook.fr',
    },
    'jimrxbnr': {
      'en': '@live.com',
      'ar': '@live.com',
      'de': '@live.com',
      'es': '@vivo.com',
      'fr': '@live.com',
      'nl': '@live.com',
    },
    'vyfir1jj': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'nl': 'Wachtwoord',
    },
    'fa9cbuau': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'nl': 'Log in',
    },
    'e22a1ibm': {
      'en': 'Forgot Password?',
      'ar': 'هل نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'nl': 'Wachtwoord vergeten?',
    },
    'a364sdw6': {
      'en': 'Or use a social account to login',
      'ar': 'أو استخدم حساب التواصل الاجتماعي لتسجيل الدخول',
      'de': 'Oder verwenden Sie ein soziales Konto, um sich anzumelden',
      'es': 'O use una cuenta social para iniciar sesión',
      'fr': 'Ou utilisez un compte social pour vous connecter',
      'nl': 'Of gebruik een sociaal account om in te loggen',
    },
    'tiv69to3': {
      'en': 'Sign Up',
      'ar': 'اشتراك',
      'de': 'Melden Sie sich an',
      'es': 'Inscribirse',
      'fr': 'S\'inscrire',
      'nl': 'Aanmelden',
    },
    'ohlnut5o': {
      'en': 'Email adresse ...',
      'ar': 'عنوان البريد الإلكتروني ...',
      'de': 'E-Mailadresse ...',
      'es': 'Direccion de correo electronico ...',
      'fr': 'Adresse email ...',
      'nl': 'E-mailadres ...',
    },
    'fgennzmg': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'nl': 'Wachtwoord',
    },
    'xf6n5n28': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'nl': 'bevestig wachtwoord',
    },
    'yw1yhuv8': {
      'en': 'Create Account',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'nl': 'Account aanmaken',
    },
    '2p1wuq8b': {
      'en': 'Or use a social account to create account',
      'ar': 'أو استخدم حسابًا اجتماعيًا لإنشاء حساب',
      'de': 'Oder verwenden Sie ein soziales Konto, um ein Konto zu erstellen',
      'es': 'O use una cuenta social para crear una cuenta',
      'fr': 'Ou utilisez un compte social pour créer un compte',
      'nl': 'Of gebruik een sociaal account om een ​​account aan te maken',
    },
  },
  // driverPostPage
  {
    'dtk2gcx8': {
      'en': 'Post Details',
      'ar': 'تفاصيل المشاركة',
      'de': 'Beitragsdetails',
      'es': 'Detalles de la publicación',
      'fr': 'Détails du message',
      'nl': 'Postdetails',
    },
    'qzc1dk1c': {
      'en': 'Departure',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'c153glam': {
      'en': 'Arrival',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '4cg8e928': {
      'en': 'Vehicle type',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'xye6anfm': {
      'en': 'Tautliner',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '729e35ur': {
      'en': 'Frigorifique',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'wle6gk7m': {
      'en': 'Bâche',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '93jkgbrb': {
      'en': 'Plateau',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '9pv44is3': {
      'en': 'Potchare',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'qlqmimnj': {
      'en': 'Porteur',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'r812bjyq': {
      'en': 'Contact',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
  },
  // myDriverPostsPage
  {
    'inzi7608': {
      'en': 'Departure',
      'ar': 'رحيل',
      'de': 'Abfahrt',
      'es': 'Partida',
      'fr': 'Départ',
      'nl': 'Vertrek',
    },
    'i3c0yumz': {
      'en': 'Destination',
      'ar': 'الوصول',
      'de': 'Ankunft',
      'es': 'Llegada',
      'fr': 'Arrivée',
      'nl': 'Aankomst',
    },
    'dn4gambs': {
      'en': '5',
      'ar': '5',
      'de': '5',
      'es': '5',
      'fr': '5',
      'nl': '5',
    },
    'erqkopsr': {
      'en': 'My posts',
      'ar': 'مشاركاتي',
      'de': 'Meine Posts',
      'es': 'Mis publicaciones',
      'fr': 'Mes publications',
      'nl': 'Mijn posts',
    },
    'zx2uobjb': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // EditDriverPostPage
  {
    'xs84fibd': {
      'en': 'From where? ...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'dey3g3va': {
      'en': 'Where to? ...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'rctvrrze': {
      'en': 'Chose a departure date ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'q7gve6md': {
      'en': 'Save changes',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '8vce4zpg': {
      'en': 'Edit post',
      'ar': 'تعديل المنشور',
      'de': 'Beitrag bearbeiten',
      'es': 'Editar post',
      'fr': 'Modifier le message',
      'nl': 'Bericht bewerken',
    },
  },
  // Splash
  {
    'b04c77kd': {
      'en': 'CargoMeet',
      'ar': 'CargoMeet',
      'de': 'CargoMeet',
      'es': 'CargoMeet',
      'fr': 'CargoMeet',
      'nl': 'CargoMeet',
    },
    'uhdgsmd4': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // DriverOnboarding1
  {
    'i43ckatd': {
      'en': 'Edit Profile',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '1obb7l96': {
      'en': 'Below are your profile details',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'hemylzug': {
      'en': 'Change Photo',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '8ndsvhrt': {
      'en': 'First Name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'vhmjxtaq': {
      'en': 'Last Name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '4qvwlxtn': {
      'en': 'User_name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'rlrdyn9a': {
      'en': 'Male',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'g0narapu': {
      'en': 'Female',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'huzpty0e': {
      'en': 'Gender...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '9ae3iytm': {
      'en': 'Search for an item...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'rgqzjz6j': {
      'en': 'Bio...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'juev111e': {
      'en': 'Your email is',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '7wafrh53': {
      'en': 'Created On:',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '7hrameij': {
      'en': 'Save & Continue',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '6d2dz0ll': {
      'en': 'Contact',
      'ar': 'اتصال',
      'de': 'Kontakt',
      'es': 'Contacto',
      'fr': 'Contact',
      'nl': 'Contact',
    },
    'y4nh147b': {
      'en': 'Enter your phone',
      'ar': 'أدخل هاتفك',
      'de': 'Geben Sie Ihr Telefon ein',
      'es': 'Introduce tu teléfono',
      'fr': 'Entrez votre téléphone',
      'nl': 'Voer uw telefoon in',
    },
    '0s1jjvhz': {
      'en': 'Ex : 0123456789',
      'ar': 'مثال: 0123456789',
      'de': 'Beispiel: 0123456789',
      'es': 'Ej: 0123456789',
      'fr': 'Ex : 0123456789',
      'nl': 'Bijv.: 0123456789',
    },
    'erq872q9': {
      'en': 'Verify',
      'ar': 'يؤكد',
      'de': 'Verifizieren',
      'es': 'Verificar',
      'fr': 'Vérifier',
      'nl': 'Verifiëren',
    },
    'jgvszs3u': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // DriverOnboarding2
  {
    'olqxihih': {
      'en':
          'Enter your info exactly as it appears on your license so we can verify your eligibility to route',
      'ar':
          'أدخل معلوماتك تمامًا كما تظهر في الترخيص الخاص بك حتى نتمكن من التحقق من أهليتك للتوجيه',
      'de':
          'Geben Sie Ihre Daten genau so ein, wie sie auf Ihrer Lizenz erscheinen, damit wir Ihre Berechtigung zur Weiterleitung überprüfen können',
      'es':
          'Ingrese su información exactamente como aparece en su licencia para que podamos verificar su elegibilidad para enrutar',
      'fr':
          'Entrez vos informations exactement telles qu\'elles apparaissent sur votre licence afin que nous puissions vérifier votre éligibilité à l\'acheminement',
      'nl':
          'Voer uw gegevens precies in zoals deze op uw licentie staan, zodat we kunnen verifiëren of u in aanmerking komt voor een route',
    },
    '0l2cmvh1': {
      'en': 'First name',
      'ar': 'الاسم الأول',
      'de': 'Vorname',
      'es': 'Nombre de pila',
      'fr': 'Prénom',
      'nl': 'Voornaam',
    },
    'iobmexuh': {
      'en': 'Last Name',
      'ar': 'اسم العائلة',
      'de': 'Familienname, Nachname',
      'es': 'Apellido',
      'fr': 'Nom de famille',
      'nl': 'Achternaam',
    },
    'xl0dl1tl': {
      'en': 'License number',
      'ar': 'رقم الرخصة',
      'de': 'Amtliches Kennzeichen',
      'es': 'Número de licencia',
      'fr': 'Numéro de licence',
      'nl': 'Licentienummer',
    },
    '6xwpmbyc': {
      'en': 'Obtention date',
      'ar': 'تاريخ الحصول',
      'de': 'Bezugsdatum',
      'es': 'Fecha de obtención',
      'fr': 'Date d\'obtention',
      'nl': 'Datum van verkrijging',
    },
    'aaprhg7y': {
      'en': 'Obtention date',
      'ar': 'تاريخ الحصول',
      'de': 'Bezugsdatum',
      'es': 'Fecha de obtención',
      'fr': 'Date d\'obtention',
      'nl': 'Datum van verkrijging',
    },
    'u85iwzc7': {
      'en': 'Driver Licence',
      'ar': 'رخصة قيادة',
      'de': 'Führerschein',
      'es': 'Licencia de conducir',
      'fr': 'Permis de conduire',
      'nl': 'Rijbewijs',
    },
    'amlzihue': {
      'en': 'Upload',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    'qyzb05ww': {
      'en': 'Clear',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    '8e6n40m6': {
      'en':
          'Enter your info exactly as it appears on your license so we can verify your eligibility to route',
      'ar':
          'أدخل معلوماتك تمامًا كما تظهر في الترخيص الخاص بك حتى نتمكن من التحقق من أهليتك للتوجيه',
      'de':
          'Geben Sie Ihre Daten genau so ein, wie sie auf Ihrer Lizenz erscheinen, damit wir Ihre Berechtigung zur Weiterleitung überprüfen können',
      'es':
          'Ingrese su información exactamente como aparece en su licencia para que podamos verificar su elegibilidad para enrutar',
      'fr':
          'Entrez vos informations exactement telles qu\'elles apparaissent sur votre licence afin que nous puissions vérifier votre éligibilité à l\'acheminement',
      'nl':
          'Voer uw gegevens precies in zoals deze op uw licentie staan, zodat we kunnen verifiëren of u in aanmerking komt voor een route',
    },
    'ww932gm3': {
      'en': 'Insurance Certificate',
      'ar': 'شهادة تأمين',
      'de': 'Versicherungszertifikat',
      'es': 'Certificado de seguro',
      'fr': 'Certificat d\'assurance',
      'nl': 'Verzekeringscertificaat',
    },
    '3dedz1dx': {
      'en': 'Upload\n',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    'xgaod956': {
      'en': 'Clear',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    'cpunjg0k': {
      'en': 'Registration Certificate',
      'ar': 'شهادة تسجيل',
      'de': 'Registrierungs-Zertifikat',
      'es': 'Certificado de registro',
      'fr': 'Certificat d\'enregistrement',
      'nl': 'Registratie certificaat',
    },
    'iqjdpxvh': {
      'en': 'Upload\n',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    '7p7csz3p': {
      'en': 'Clear',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    'udl4tzsr': {
      'en': 'Vehicle Plate Number',
      'ar': 'رقم لوحة المركبة',
      'de': 'Fahrzeugkennzeichen',
      'es': 'Número de placa del vehículo',
      'fr': 'Numéro de plaque du véhicule',
      'nl': 'Voertuigplaatnummer',
    },
    '9ce44p46': {
      'en': '   XX-XX-XX',
      'ar': 'XX-XX-XX',
      'de': 'XX-XX-XX',
      'es': 'XX-XX-XX',
      'fr': 'XX-XX-XX',
      'nl': 'XX-XX-XX',
    },
    'x5nhvcnp': {
      'en': 'Vehicle Brand',
      'ar': 'ماركة السيارة',
      'de': 'Fahrzeugmarke',
      'es': 'Marca del vehículo',
      'fr': 'Marque du véhicule',
      'nl': 'Voertuig merk',
    },
    '3g5v8v90': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'eztb5c8u': {
      'en': 'MAN',
      'ar': 'رجل',
      'de': 'MANN',
      'es': 'HOMBRE',
      'fr': 'HOMME',
      'nl': 'MAN',
    },
    'q6ly5ycc': {
      'en': 'RENAULT',
      'ar': 'رينو',
      'de': 'RENAULT',
      'es': 'RENAULT',
      'fr': 'RENAULT',
      'nl': 'RENAULT',
    },
    '59mr14ly': {
      'en': 'DAF',
      'ar': 'داف',
      'de': 'DAF',
      'es': 'DAF',
      'fr': 'DAF',
      'nl': 'DAF',
    },
    'wjy2fw4i': {
      'en': 'MERCEDES-BENZ',
      'ar': 'مرسيدس بنز',
      'de': 'MERCEDES-BENZ',
      'es': 'MERCEDES-BENZ',
      'fr': 'MERCEDES-BENZ',
      'nl': 'MERCEDES-BENZ',
    },
    '8e5ofsj0': {
      'en': 'CITROEN',
      'ar': 'سيتروين',
      'de': 'CITROEN',
      'es': 'CITROÉN',
      'fr': 'CITROËN',
      'nl': 'CITROEN',
    },
    '1cc3jyj8': {
      'en': 'NISSAN',
      'ar': 'نيسان',
      'de': 'NISSAN',
      'es': 'NISSAN',
      'fr': 'NISSAN',
      'nl': 'NISSAN',
    },
    'vmwg67hm': {
      'en': 'VOLVO',
      'ar': 'فولفو',
      'de': 'VOLVO',
      'es': 'VOLVO',
      'fr': 'VOLVO',
      'nl': 'VOLVO',
    },
    'tdwn69cx': {
      'en': 'AUTRE ...',
      'ar': 'آخر ...',
      'de': 'AUTRE ...',
      'es': 'OTRA...',
      'fr': 'AUTRE...',
      'nl': 'AUTRE ...',
    },
    '02za3m9p': {
      'en': 'Search for an item...',
      'ar': 'البحث عن عنصر...',
      'de': 'Nach einem Artikel suchen...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'nl': 'Zoek een artikel...',
    },
    'zj1cecf5': {
      'en': 'Select your vehicle type',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'nmom06ch': {
      'en': 'Tautliner',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'pc38jvs8': {
      'en': 'Frigorifique',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '4u5jicld': {
      'en': 'Potchare',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'lumtdcn5': {
      'en': 'Porteur',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'pj2ovrqz': {
      'en': 'Plateau',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'crszua1l': {
      'en': 'Tracteur',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'xof7o3bj': {
      'en': 'Van',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'ma6sxbrz': {
      'en': 'Let\'s Drive',
      'ar': 'دعنا نقود',
      'de': 'Fahren wir los',
      'es': 'Manejemos',
      'fr': 'Conduisons',
      'nl': 'Laten we rijden',
    },
    '7jxa9o79': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // Onboardnig1-DrievrOrClient
  {
    'j5f3coot': {
      'en': 'What kind of service do you provide?',
      'ar': 'ما نوع الخدمة التي تقدمها؟',
      'de': 'Welche Art von Service bieten Sie an?',
      'es': '¿Qué tipo de servicio brindan?',
      'fr': 'Quel type de service fournissez-vous ?',
      'nl': 'Wat voor soort dienst levert u?',
    },
    '9qb1gfun': {
      'en': 'Transporter',
      'ar': 'الناقل',
      'de': 'Transporter',
      'es': 'transportador',
      'fr': 'Transporteur',
      'nl': 'Transporteur',
    },
    'lm7inm5c': {
      'en': 'I provide trasportation services, \nI own lorries',
      'ar': 'انا اقدم خدمات النقل\nأنا أملك الشاحنات',
      'de': 'Ich biete Transportdienstleistungen an,\nIch besitze Lastwagen',
      'es': 'Brindo servicios de transporte,\ntengo camiones',
      'fr': 'Je fournis des services de transport,\nJe possède des camions',
      'nl': 'Ik verleen transportdiensten,\nIk ben eigenaar van vrachtwagens',
    },
    '5ei7cswr': {
      'en': 'Shipper',
      'ar': 'الشاحن',
      'de': 'Absender',
      'es': 'Expedidor',
      'fr': 'Expéditeur',
      'nl': 'Verzender',
    },
    'ax9ho1el': {
      'en': 'I own the good looking for \ntransportion services',
      'ar': 'أنا أملك الخير الذي تبحث عنه\nخدمات النقل',
      'de': 'Ich besitze das Gute, das ich suche\nTransportdienstleistungen',
      'es': 'Soy dueño del buen aspecto\nservicios de transporte',
      'fr': 'Je possède le bien recherché\nservices de transport',
      'nl': 'Ik bezit de goede zoekt\ntransportdiensten',
    },
    'g7pxu65f': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // listShippersPostPage
  {
    'vjdt8zm5': {
      'en': 'Departure',
      'ar': 'رحيل',
      'de': 'Abfahrt',
      'es': 'Partida',
      'fr': 'Départ',
      'nl': 'Vertrek',
    },
    'wxhu97kd': {
      'en': 'Arrival',
      'ar': 'الوصول',
      'de': 'Ankunft',
      'es': 'Llegada',
      'fr': 'Arrivée',
      'nl': 'Aankomst',
    },
    '8ftxv0i5': {
      'en': '5',
      'ar': '5',
      'de': '5',
      'es': '5',
      'fr': '5',
      'nl': '5',
    },
    'o1movxky': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // CreateDriverPostPage
  {
    'kz2nj3ex': {
      'en': 'From where? ...',
      'ar': 'من اين؟ ...',
      'de': 'Wovon? ...',
      'es': '¿De donde? ...',
      'fr': 'D\'où? ...',
      'nl': 'Waarvan? ...',
    },
    'knzz4dde': {
      'en': 'Where to? ...',
      'ar': 'إلى أين؟ ...',
      'de': 'Wohin? ...',
      'es': '¿A donde? ...',
      'fr': 'Où aller ? ...',
      'nl': 'Waarheen? ...',
    },
    'd07yyv0t': {
      'en': 'Chose a departure date ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '2v4qgmdw': {
      'en': 'Publish',
      'ar': 'ينشر',
      'de': 'Veröffentlichen',
      'es': 'Publicar',
      'fr': 'Publier',
      'nl': 'Publiceren',
    },
    'v8xfbc8i': {
      'en': 'Create a post',
      'ar': 'إنشاء مشاركة',
      'de': 'Erstellen Sie einen Beitrag',
      'es': 'Crear una publicación',
      'fr': 'Créer un message',
      'nl': 'Maak een bericht',
    },
    'fkaupmwl': {
      'en': 'Create',
      'ar': 'يخلق',
      'de': 'Erstellen',
      'es': 'Crear',
      'fr': 'Créer',
      'nl': 'Creëren',
    },
  },
  // ShipperProfile
  {
    'li417fk5': {
      'en': 'Profile',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'nl': 'Profiel',
    },
    'qmsk6ot5': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'nl': 'Bewerk profiel',
    },
    'a5bqntcf': {
      'en': 'My posts',
      'ar': 'مشاركاتي',
      'de': 'Meine Posts',
      'es': 'Mis publicaciones',
      'fr': 'Mes publications',
      'nl': 'Mijn posts',
    },
    'jrtytad5': {
      'en': 'Notification Settings',
      'ar': 'إعدادات الإشعار',
      'de': 'Benachrichtigungseinstellungen',
      'es': 'Configuración de las notificaciones',
      'fr': 'Paramètres de notification',
      'nl': 'Notificatie instellingen',
    },
    'omxj7oky': {
      'en': 'Account Information',
      'ar': 'معلومات الحساب',
      'de': 'Kontoinformationen',
      'es': 'Información de la cuenta',
      'fr': 'Information sur le compte',
      'nl': 'Account Informatie',
    },
    'ypwh1bxz': {
      'en': 'Phone Number',
      'ar': 'رقم التليفون',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'nl': 'Telefoonnummer',
    },
    '52rm2i4d': {
      'en': 'Address',
      'ar': 'عنوان',
      'de': 'Adresse',
      'es': 'DIRECCIÓN',
      'fr': 'Adresse',
      'nl': 'Adres',
    },
    'r7elmd0y': {
      'en': 'Log Out',
      'ar': 'تسجيل خروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'nl': 'Uitloggen',
    },
    'm0ap1vcr': {
      'en': 'Delete my account ',
      'ar': 'احذف حسابي',
      'de': 'Mein Konto löschen',
      'es': 'Borrar mi cuenta',
      'fr': 'Supprimer mon compte',
      'nl': 'Verwijder mijn account',
    },
    'wrtyit6j': {
      'en': 'Profile',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'nl': 'Profiel',
    },
  },
  // ShipperOnboarding1
  {
    'ihrcropw': {
      'en': 'Edit Profile',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'jfjpono1': {
      'en': 'Below are your profile details',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'wp5g2m42': {
      'en': 'Change Photo',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'be3288ya': {
      'en': 'First Name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '6qs3f4g6': {
      'en': 'Last Name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'tsqcphnt': {
      'en': 'User_name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'utj27hly': {
      'en': 'Male',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'yqh4ekn9': {
      'en': 'Female',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'zjkihs77': {
      'en': 'Gender...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'uyadumty': {
      'en': 'Search for an item...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'j35q041r': {
      'en': 'Bio...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'qmtcji0b': {
      'en': 'Your email is',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'a4fugscj': {
      'en': 'Joined On:',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'fr33fp87': {
      'en': 'Save Changes',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '8vuiwkay': {
      'en': 'Contact',
      'ar': 'اتصال',
      'de': 'Kontakt',
      'es': 'Contacto',
      'fr': 'Contact',
      'nl': 'Contact',
    },
    'jaa1uzbd': {
      'en': 'Enter your phone',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'vfv5l5kq': {
      'en': 'Ex : 0123456789',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'cp8g38fj': {
      'en': 'Verify',
      'ar': 'يؤكد',
      'de': 'Verifizieren',
      'es': 'Verificar',
      'fr': 'Vérifier',
      'nl': 'Verifiëren',
    },
    'hoic8s2s': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // ShipperOnboarding2
  {
    '5ryyn4j1': {
      'en':
          'Enter your info exactly as it appears on your license so we can verify your account.',
      'ar':
          'أدخل معلوماتك تمامًا كما تظهر في الترخيص الخاص بك حتى نتمكن من التحقق من حسابك.',
      'de':
          'Geben Sie Ihre Daten genau so ein, wie sie auf Ihrer Lizenz erscheinen, damit wir Ihr Konto überprüfen können.',
      'es':
          'Ingrese su información exactamente como aparece en su licencia para que podamos verificar su cuenta.',
      'fr':
          'Entrez vos informations exactement telles qu\'elles apparaissent sur votre licence afin que nous puissions vérifier votre compte.',
      'nl':
          'Voer uw gegevens precies in zoals deze op uw licentie staan, zodat we uw account kunnen verifiëren.',
    },
    '1dzmu2fx': {
      'en': 'Company Name',
      'ar': 'اسم الشركة',
      'de': 'Name der Firma',
      'es': 'nombre de empresa',
      'fr': 'Nom de l\'entreprise',
      'nl': 'Bedrijfsnaam',
    },
    'd07xqwxg': {
      'en': 'Siret Number',
      'ar': 'رقم السرت',
      'de': 'Siret-Nummer',
      'es': 'Número de sirena',
      'fr': 'Numéro de Siret',
      'nl': 'Siret-nummer',
    },
    'og5ml2ev': {
      'en': 'Siren number',
      'ar': 'رقم صفارة الإنذار',
      'de': 'Sirenennummer',
      'es': 'numero de sirena',
      'fr': 'Numéro de sirène',
      'nl': 'Sirene nummer',
    },
    'i1ksoww6': {
      'en': 'Adresse',
      'ar': 'العنوان',
      'de': 'Adresse',
      'es': 'dirección',
      'fr': 'Adresse',
      'nl': 'Adres',
    },
    'vhbczswe': {
      'en': 'Created date',
      'ar': 'تاريخ الإنشاء',
      'de': 'Erstellungsdatum',
      'es': 'Fecha de creación',
      'fr': 'Date de création',
      'nl': 'Aanmaakdatum',
    },
    '3nvey7bn': {
      'en': 'Company Licence',
      'ar': 'رخصة الشركة',
      'de': 'Firmenlizenz',
      'es': 'Licencia de empresa',
      'fr': 'Licence d\'entreprise',
      'nl': 'Bedrijfslicentie',
    },
    '1p3rqqje': {
      'en': 'Upload\n',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    's4q3a1wv': {
      'en': 'Upload\n',
      'ar': 'رفع',
      'de': 'Hochladen',
      'es': 'Subir',
      'fr': 'Télécharger',
      'nl': 'Uploaden',
    },
    '4vl6yiv7': {
      'en': 'Let\'s GO',
      'ar': 'دعنا نذهب',
      'de': 'Lass uns gehen',
      'es': 'Vamos',
      'fr': 'Allons-y',
      'nl': 'Laten we gaan',
    },
    '23wqk1a9': {
      'en': 'Company Informtions',
      'ar': 'معلومات الشركة',
      'de': 'Unternehmensinformationen',
      'es': 'Información de la empresa',
      'fr': 'Informations sur l\'entreprise',
      'nl': 'Bedrijfsinformatie',
    },
    '5aihzx9x': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // CreateShipperPostPage
  {
    'rchy47rk': {
      'en': 'From where? ...',
      'ar': 'من اين؟ ...',
      'de': 'Wovon? ...',
      'es': '¿De donde? ...',
      'fr': 'D\'où? ...',
      'nl': 'Waarvan? ...',
    },
    '98lqales': {
      'en': 'Where to? ...',
      'ar': 'إلى أين؟ ...',
      'de': 'Wohin? ...',
      'es': '¿A donde? ...',
      'fr': 'Où aller ? ...',
      'nl': 'Waarheen? ...',
    },
    'bgbkfbdh': {
      'en': 'Select a truck type that you need for your Cargo.',
      'ar': 'حدد نوع الشاحنة التي تحتاجها لشحنتك.',
      'de': 'Wählen Sie einen LKW-Typ aus, den Sie für Ihre Fracht benötigen.',
      'es': 'Seleccione el tipo de camión que necesita para su carga.',
      'fr':
          'Sélectionnez un type de camion dont vous avez besoin pour votre cargaison.',
      'nl': 'Selecteer het vrachtwagentype dat u nodig heeft voor uw Cargo.',
    },
    'q2w4ruvf': {
      'en': 'Tautliner',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'tedgdjyi': {
      'en': 'Frigorifique',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'dhw08oxb': {
      'en': 'potchare',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '3b7jo0c8': {
      'en': 'Porteur',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'z8blwwe4': {
      'en': 'Plateau',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'ccha3gt4': {
      'en': 'Tracteur',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '47cxpdos': {
      'en': 'Van',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'x3vizgqe': {
      'en': 'Weight KG',
      'ar': 'الوزن كجم',
      'de': 'Gewicht (kg',
      'es': 'Peso kilos',
      'fr': 'Poids (kg',
      'nl': 'Gewicht (kg',
    },
    '8n64pgba': {
      'en': 'Price',
      'ar': 'سعر',
      'de': 'Preis',
      'es': 'Precio',
      'fr': 'Prix',
      'nl': 'Prijs',
    },
    'hainx82j': {
      'en': '€',
      'ar': '€',
      'de': '€',
      'es': '€',
      'fr': '€',
      'nl': '€',
    },
    '7fiw9qzt': {
      'en': '\$',
      'ar': '\$',
      'de': '\$',
      'es': 'ps',
      'fr': '\$',
      'nl': '\$',
    },
    'kuxakr2r': {
      'en': 'MAD',
      'ar': 'مجنون',
      'de': 'VERRÜCKT',
      'es': 'ENOJADO',
      'fr': 'FOU',
      'nl': 'BOOS',
    },
    'auaxelut': {
      'en': '€',
      'ar': '€',
      'de': '€',
      'es': '€',
      'fr': '€',
      'nl': '€',
    },
    '2m29y9uu': {
      'en': 'Search for an item...',
      'ar': 'البحث عن عنصر...',
      'de': 'Nach einem Artikel suchen...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'nl': 'Zoek een artikel...',
    },
    'v8x4wjdc': {
      'en': 'Publish',
      'ar': 'ينشر',
      'de': 'Veröffentlichen',
      'es': 'Publicar',
      'fr': 'Publier',
      'nl': 'Publiceren',
    },
    'dlacri24': {
      'en': 'Create a post',
      'ar': 'إنشاء مشاركة',
      'de': 'Erstellen Sie einen Beitrag',
      'es': 'Crear una publicación',
      'fr': 'Créer un message',
      'nl': 'Maak een bericht',
    },
    '62rjp2ak': {
      'en': 'Create',
      'ar': 'يخلق',
      'de': 'Erstellen',
      'es': 'Crear',
      'fr': 'Créer',
      'nl': 'Creëren',
    },
  },
  // ShipperPostPage
  {
    'a7g2r2zo': {
      'en': 'Departure',
      'ar': 'رحيل',
      'de': 'Abfahrt',
      'es': 'Partida',
      'fr': 'Départ',
      'nl': 'Vertrek',
    },
    '6cw891qc': {
      'en': 'Arrival',
      'ar': 'الوصول',
      'de': 'Ankunft',
      'es': 'Llegada',
      'fr': 'Arrivée',
      'nl': 'Aankomst',
    },
    'lmk8f2vz': {
      'en': 'Vehicle type',
      'ar': 'نوع السيارة',
      'de': 'Fahrzeugtyp',
      'es': 'Tipo de vehiculo',
      'fr': 'Type de véhicule',
      'nl': 'Voertuigtype',
    },
    'wl7gfht2': {
      'en': 'Tautliner',
      'ar': 'توتلينر',
      'de': 'Tautliner',
      'es': 'tautliner',
      'fr': 'Tautliner',
      'nl': 'Tautliner',
    },
    'lwojql7j': {
      'en': 'Frigorifique',
      'ar': 'فريجوريفيك',
      'de': 'Frigorifique',
      'es': 'Frigorifique',
      'fr': 'Frigorifique',
      'nl': 'Frigorifique',
    },
    'cs5dd1eb': {
      'en': 'Bâche',
      'ar': 'باش',
      'de': 'Bache',
      'es': 'Bache',
      'fr': 'Bâche',
      'nl': 'Bache',
    },
    'xf296goz': {
      'en': 'Plateau',
      'ar': 'هضبة',
      'de': 'Plateau',
      'es': 'Meseta',
      'fr': 'Plateau',
      'nl': 'Plateau',
    },
    's1pxirak': {
      'en': 'Potchare',
      'ar': 'بوتشاري',
      'de': 'Potchare',
      'es': 'potaje',
      'fr': 'Potcharé',
      'nl': 'Potchare',
    },
    '0b0m8t3u': {
      'en': 'Porteur',
      'ar': 'بورتيور',
      'de': 'Porteur',
      'es': 'portero',
      'fr': 'Porteur',
      'nl': 'Porteur',
    },
    'gvkcdbsw': {
      'en': 'Contact',
      'ar': 'احجز الآن',
      'de': 'Buchen Sie jetzt',
      'es': 'Reservar ahora',
      'fr': 'Reserve maintenant',
      'nl': 'Boek nu',
    },
    '2xbkpwpe': {
      'en': 'Details',
      'ar': 'تفاصيل',
      'de': 'Einzelheiten',
      'es': 'Detalles',
      'fr': 'Détails',
      'nl': 'Details',
    },
  },
  // EditShipperPostPage
  {
    'qd4xomt0': {
      'en': 'From where? ...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'jni8s1dp': {
      'en': 'Where to? ...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'c25lh0c8': {
      'en': 'Select a truck type that you need for your Cargo.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '7ye5t0q1': {
      'en': 'Tautliner',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'k5qqpvj3': {
      'en': 'Frigorifique',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '2x3d1462': {
      'en': 'Bâche',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'pc5sumgx': {
      'en': 'Plateau',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '0bfskdv7': {
      'en': 'Potchare',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'rt5ox6ta': {
      'en': 'Porteur',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'bk5ed7qh': {
      'en': 'Weight KG',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'w7r8drq6': {
      'en': 'Price',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'f4kprfr5': {
      'en': '€',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '2im0imlv': {
      'en': '\$',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '48xonyvv': {
      'en': 'MAD',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'shghxssu': {
      'en': '€',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'yv59zrwb': {
      'en': 'Search for an item...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'a8zm8q0v': {
      'en': 'Save Changes',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '8l8al340': {
      'en': 'Edit post',
      'ar': 'تعديل المنشور',
      'de': 'Beitrag bearbeiten',
      'es': 'Editar post',
      'fr': 'Modifier le message',
      'nl': 'Bericht bewerken',
    },
  },
  // myShipperPostsPage
  {
    '3hvdp8xl': {
      'en': 'Departure',
      'ar': 'رحيل',
      'de': 'Abfahrt',
      'es': 'Partida',
      'fr': 'Départ',
      'nl': 'Vertrek',
    },
    '5zhjwjqo': {
      'en': 'Arrival',
      'ar': 'الوصول',
      'de': 'Ankunft',
      'es': 'Llegada',
      'fr': 'Arrivée',
      'nl': 'Aankomst',
    },
    'kpcmhagt': {
      'en': 'My posts',
      'ar': 'مشاركاتي',
      'de': 'Meine Posts',
      'es': 'Mis publicaciones',
      'fr': 'Mes publications',
      'nl': 'Mijn posts',
    },
    '3lqboc50': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'nl': 'Thuis',
    },
  },
  // ChatPage
  {
    'vtvops8y': {
      'en': 'Type somthing...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'xq3ng5rk': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
  },
  // ChangePhoto
  {
    '3n0fn8bq': {
      'en': 'Change Photo',
      'ar': 'غير الصوره',
      'de': 'Foto ändern',
      'es': 'Cambiar foto',
      'fr': 'Changer la photo',
      'nl': 'Verander foto',
    },
    'ce2rz3ou': {
      'en': 'Upload Image',
      'ar': 'تحميل الصور',
      'de': 'Bild hochladen',
      'es': 'Cargar imagen',
      'fr': 'Télécharger une image',
      'nl': 'Afbeelding uploaden',
    },
    '9bfr32yt': {
      'en': 'Save Changes',
      'ar': 'حفظ التغييرات',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'nl': 'Wijzigingen opslaan',
    },
  },
  // EditShipperPostButtonSheet
  {
    '6z2dnmwg': {
      'en': 'Wich change do you want to do?',
      'ar': 'ما هو التغيير الذي تريد القيام به؟',
      'de': 'Welche Veränderung möchten Sie vornehmen?',
      'es': '¿Qué cambio quieres hacer?',
      'fr': 'Quel changement souhaites-tu faire ?',
      'nl': 'Welke verandering wil je doorvoeren?',
    },
    '82d2mqts': {
      'en': 'If you delee your post you will lose it forever.',
      'ar': 'إذا قمت بحذف مشاركتك فسوف تفقدها إلى الأبد.',
      'de': 'Wenn Sie Ihren Beitrag löschen, ist er für immer verloren.',
      'es': 'Si eliminas tu publicación la perderás para siempre.',
      'fr': 'Si vous supprimez votre message, vous le perdrez pour toujours.',
      'nl': 'Als je je bericht verwijdert, ben je het voor altijd kwijt.',
    },
    'pfr0279p': {
      'en': 'Share',
      'ar': 'يشارك',
      'de': 'Aktie',
      'es': 'Compartir',
      'fr': 'Partager',
      'nl': 'Deel',
    },
    '50jjsmf3': {
      'en': 'Get Link',
      'ar': 'خذ رابط',
      'de': 'Link abrufen',
      'es': 'Conseguir enlace',
      'fr': 'Obtenir le lien',
      'nl': 'Krijg link',
    },
    'wja40oku': {
      'en': 'Edit',
      'ar': 'يحرر',
      'de': 'Bearbeiten',
      'es': 'Editar',
      'fr': 'Modifier',
      'nl': 'Bewerking',
    },
    'xqi0olij': {
      'en': 'Delete',
      'ar': 'يمسح',
      'de': 'Löschen',
      'es': 'Borrar',
      'fr': 'Supprimer',
      'nl': 'Verwijderen',
    },
  },
  // ShipperPhoneNumberConfirmation
  {
    'i0ewtk01': {
      'en': 'Enter the confirmation PIN below',
      'ar': 'أدخل رقم التعريف الشخصي للتأكيد أدناه',
      'de': 'Geben Sie unten die Bestätigungs-PIN ein',
      'es': 'Ingrese el PIN de confirmación a continuación',
      'fr': 'Entrez le code PIN de confirmation ci-dessous',
      'nl': 'Voer hieronder de bevestigingspincode in',
    },
    '5fevvhq2': {
      'en':
          'Please confirm your phone number with the code you have recieved or you will  recieve in a few seconds.',
      'ar':
          'يرجى تأكيد رقم هاتفك باستخدام الرمز الذي تلقيته وإلا ستصلك خلال ثوانٍ قليلة.',
      'de':
          'Bitte bestätigen Sie Ihre Telefonnummer mit dem Code, den Sie erhalten haben, sonst erhalten Sie ihn in wenigen Sekunden.',
      'es':
          'Confirma tu número de teléfono con el código que has recibido o lo recibirás en unos segundos.',
      'fr':
          'Veuillez confirmer votre numéro de téléphone avec le code que vous avez reçu ou vous le recevrez dans quelques secondes.',
      'nl':
          'Bevestig uw telefoonnummer met de code die u heeft ontvangen of die u binnen enkele seconden ontvangt.',
    },
    'zk2z72k3': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'nl': 'Annuleren',
    },
    'p3ryyk61': {
      'en': 'Verify Code',
      'ar': 'التحقق من كود',
      'de': 'Code überprüfen',
      'es': 'Código de verificación',
      'fr': 'Vérifier le code',
      'nl': 'Code verifiëren',
    },
  },
  // ModalEditDriverProfile
  {
    'ni6gv3ds': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'nl': 'Bewerk profiel',
    },
    'lvq27nb8': {
      'en': 'Below are your profile details',
      'ar': 'فيما يلي تفاصيل ملفك الشخصي',
      'de': 'Nachfolgend finden Sie Ihre Profildetails',
      'es': 'A continuación se muestran los detalles de su perfil.',
      'fr': 'Ci-dessous les détails de votre profil',
      'nl': 'Hieronder staan ​​uw profielgegevens',
    },
    'ygvdni8c': {
      'en': 'Change Photo',
      'ar': 'غير الصوره',
      'de': 'Foto ändern',
      'es': 'Cambiar foto',
      'fr': 'Changer la photo',
      'nl': 'Verander foto',
    },
    'm6afd48w': {
      'en': 'First Name',
      'ar': 'الاسم الأول',
      'de': 'Vorname',
      'es': 'Nombre de pila',
      'fr': 'Prénom',
      'nl': 'Voornaam',
    },
    'hsi2n2ta': {
      'en': 'Last Name',
      'ar': 'اسم العائلة',
      'de': 'Familienname, Nachname',
      'es': 'Apellido',
      'fr': 'Nom de famille',
      'nl': 'Achternaam',
    },
    '7zxv0kk0': {
      'en': 'User_name',
      'ar': 'اسم المستخدم',
      'de': 'Nutzername',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'nl': 'Gebruikersnaam',
    },
    'mp1o8620': {
      'en': 'Male',
      'ar': 'ذكر',
      'de': 'Männlich',
      'es': 'Masculino',
      'fr': 'Mâle',
      'nl': 'Mannelijk',
    },
    'ii39ffbf': {
      'en': 'Female',
      'ar': 'أنثى',
      'de': 'Weiblich',
      'es': 'Femenino',
      'fr': 'Femelle',
      'nl': 'Vrouwelijk',
    },
    'm97njfks': {
      'en': 'Gender...',
      'ar': 'جنس...',
      'de': 'Geschlecht...',
      'es': 'Género...',
      'fr': 'Genre...',
      'nl': 'Geslacht...',
    },
    'teeud058': {
      'en': 'Search for an item...',
      'ar': 'البحث عن عنصر...',
      'de': 'Nach einem Artikel suchen...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'nl': 'Zoek een artikel...',
    },
    'm8uqfedl': {
      'en': 'Bio...',
      'ar': 'السيرة الذاتية...',
      'de': 'Bio...',
      'es': 'Biografía...',
      'fr': 'Biographie...',
      'nl': 'Bio...',
    },
    'kfsp5knr': {
      'en': 'Your email is',
      'ar': 'البريد الإلكتروني الخاص بك هو',
      'de': 'Ihre E-Mail lautet',
      'es': 'Tu correo electrónico es',
      'fr': 'Votre email est',
      'nl': 'Je e-mailadres is',
    },
    'fvfq24es': {
      'en': 'Created On:',
      'ar': 'تم إنشاؤها على:',
      'de': 'Erstellt am:',
      'es': 'Creado en:',
      'fr': 'Créé sur:',
      'nl': 'Gemaakt op:',
    },
    's1jf6yw9': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'nl': 'Annuleren',
    },
    'cl639jex': {
      'en': 'Save Changes',
      'ar': 'حفظ التغييرات',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'nl': 'Wijzigingen opslaan',
    },
  },
  // Notifications
  {
    '9hahfun9': {
      'en': 'Notifications',
      'ar': 'إشعارات',
      'de': 'Benachrichtigungen',
      'es': 'Notificaciones',
      'fr': 'Notifications',
      'nl': 'Meldingen',
    },
    'etalwrk0': {
      'en': 'Below are some recent alerts for you.',
      'ar': 'فيما يلي بعض التنبيهات الأخيرة لك.',
      'de':
          'Nachfolgend finden Sie einige aktuelle Benachrichtigungen für Sie.',
      'es': 'A continuación se muestran algunas alertas recientes para usted.',
      'fr': 'Vous trouverez ci-dessous quelques alertes récentes pour vous.',
      'nl': 'Hieronder vindt u enkele recente waarschuwingen voor u.',
    },
    '4tzljlyy': {
      'en': 'New',
      'ar': 'جديد',
      'de': 'Neu',
      'es': 'Nuevo',
      'fr': 'Nouveau',
      'nl': 'Nieuw',
    },
    '666b07kl': {
      'en': 'New Product View',
      'ar': 'عرض منتج جديد',
      'de': 'Neue Produktansicht',
      'es': 'Nuevo producto Ver',
      'fr': 'Nouveau produit',
      'nl': 'Nieuwe productweergave',
    },
    'uxbthxfe': {
      'en': 'Sally Mandrus, viewed your product',
      'ar': 'سالي مندروس، شاهدت منتجك',
      'de': 'Sally Mandrus, hat Ihr Produkt angesehen',
      'es': 'Sally Mandrus, vio su producto',
      'fr': 'Sally Mandrus, vous avez consulté votre produit',
      'nl': 'Sally Mandrus, heb uw product bekeken',
    },
    '707m1sk3': {
      'en': '3m ago',
      'ar': 'منذ 3 م',
      'de': 'Vor 3m',
      'es': 'hace 3m',
      'fr': 'il y a 3 mois',
      'nl': '3m geleden',
    },
    '7t7gzdkr': {
      'en': 'New Product View',
      'ar': 'عرض منتج جديد',
      'de': 'Neue Produktansicht',
      'es': 'Nuevo producto Ver',
      'fr': 'Nouveau produit',
      'nl': 'Nieuwe productweergave',
    },
    'cbdj05hx': {
      'en': 'Sally Mandrus, viewed your product',
      'ar': 'سالي مندروس، شاهدت منتجك',
      'de': 'Sally Mandrus, hat Ihr Produkt angesehen',
      'es': 'Sally Mandrus, vio su producto',
      'fr': 'Sally Mandrus, vous avez consulté votre produit',
      'nl': 'Sally Mandrus, heb uw product bekeken',
    },
    'tv62ghvm': {
      'en': '3m ago',
      'ar': 'منذ 3 م',
      'de': 'Vor 3m',
      'es': 'hace 3m',
      'fr': 'il y a 3 mois',
      'nl': '3m geleden',
    },
    'pydq24yl': {
      'en': 'All',
      'ar': 'الجميع',
      'de': 'Alle',
      'es': 'Todo',
      'fr': 'Tous',
      'nl': 'Alle',
    },
    'm7jng2z9': {
      'en': 'New Product View',
      'ar': 'عرض منتج جديد',
      'de': 'Neue Produktansicht',
      'es': 'Nuevo producto Ver',
      'fr': 'Nouveau produit',
      'nl': 'Nieuwe productweergave',
    },
    '13w3rvux': {
      'en': 'Sally Mandrus, viewed your product',
      'ar': 'سالي مندروس، شاهدت منتجك',
      'de': 'Sally Mandrus, hat Ihr Produkt angesehen',
      'es': 'Sally Mandrus, vio su producto',
      'fr': 'Sally Mandrus, vous avez consulté votre produit',
      'nl': 'Sally Mandrus, heb uw product bekeken',
    },
    'x25e7ujc': {
      'en': '3m ago',
      'ar': 'منذ 3 م',
      'de': 'Vor 3m',
      'es': 'hace 3m',
      'fr': 'il y a 3 mois',
      'nl': '3m geleden',
    },
    'os1p9g6e': {
      'en': 'New Product View',
      'ar': 'عرض منتج جديد',
      'de': 'Neue Produktansicht',
      'es': 'Nuevo producto Ver',
      'fr': 'Nouveau produit',
      'nl': 'Nieuwe productweergave',
    },
    'y0bmyfo6': {
      'en': 'Sally Mandrus, viewed your product',
      'ar': 'سالي مندروس، شاهدت منتجك',
      'de': 'Sally Mandrus, hat Ihr Produkt angesehen',
      'es': 'Sally Mandrus, vio su producto',
      'fr': 'Sally Mandrus, vous avez consulté votre produit',
      'nl': 'Sally Mandrus, heb uw product bekeken',
    },
    'r25lqqcf': {
      'en': '3m ago',
      'ar': 'منذ 3 م',
      'de': 'Vor 3m',
      'es': 'hace 3m',
      'fr': 'il y a 3 mois',
      'nl': '3m geleden',
    },
    '6en774pb': {
      'en': 'New Product View',
      'ar': 'عرض منتج جديد',
      'de': 'Neue Produktansicht',
      'es': 'Nuevo producto Ver',
      'fr': 'Nouveau produit',
      'nl': 'Nieuwe productweergave',
    },
    'rgpd188q': {
      'en': 'Sally Mandrus, viewed your product',
      'ar': 'سالي مندروس، شاهدت منتجك',
      'de': 'Sally Mandrus, hat Ihr Produkt angesehen',
      'es': 'Sally Mandrus, vio su producto',
      'fr': 'Sally Mandrus, vous avez consulté votre produit',
      'nl': 'Sally Mandrus, heb uw product bekeken',
    },
    'lw77yro1': {
      'en': '3m ago',
      'ar': 'منذ 3 م',
      'de': 'Vor 3m',
      'es': 'hace 3m',
      'fr': 'il y a 3 mois',
      'nl': '3m geleden',
    },
    'xzpyadyu': {
      'en': 'New Product View',
      'ar': 'عرض منتج جديد',
      'de': 'Neue Produktansicht',
      'es': 'Nuevo producto Ver',
      'fr': 'Nouveau produit',
      'nl': 'Nieuwe productweergave',
    },
    'acjd59tr': {
      'en': 'Sally Mandrus, viewed your product',
      'ar': 'سالي مندروس، شاهدت منتجك',
      'de': 'Sally Mandrus, hat Ihr Produkt angesehen',
      'es': 'Sally Mandrus, vio su producto',
      'fr': 'Sally Mandrus, vous avez consulté votre produit',
      'nl': 'Sally Mandrus, heb uw product bekeken',
    },
    'mjmsl9dv': {
      'en': '3m ago',
      'ar': 'منذ 3 م',
      'de': 'Vor 3m',
      'es': 'hace 3m',
      'fr': 'il y a 3 mois',
      'nl': '3m geleden',
    },
  },
  // EditDrievrPostButtonSheet
  {
    '2yp7x7ds': {
      'en': 'Wich change do you want to do?',
      'ar': 'ما هو التغيير الذي تريد القيام به؟',
      'de': 'Welche Veränderung möchten Sie vornehmen?',
      'es': '¿Qué cambio quieres hacer?',
      'fr': 'Quel changement souhaites-tu faire ?',
      'nl': 'Welke verandering wil je doorvoeren?',
    },
    '0g0r90sv': {
      'en': 'If you delee your post you will lose it forever.',
      'ar': 'إذا قمت بحذف مشاركتك فسوف تفقدها إلى الأبد.',
      'de': 'Wenn Sie Ihren Beitrag löschen, ist er für immer verloren.',
      'es': 'Si eliminas tu publicación la perderás para siempre.',
      'fr': 'Si vous supprimez votre message, vous le perdrez pour toujours.',
      'nl': 'Als je je bericht verwijdert, ben je het voor altijd kwijt.',
    },
    '62uowy4t': {
      'en': 'Share',
      'ar': 'يشارك',
      'de': 'Aktie',
      'es': 'Compartir',
      'fr': 'Partager',
      'nl': 'Deel',
    },
    'l4akfwd8': {
      'en': 'Get Link',
      'ar': 'خذ رابط',
      'de': 'Link abrufen',
      'es': 'Conseguir enlace',
      'fr': 'Obtenir le lien',
      'nl': 'Krijg link',
    },
    '7fmv9eb7': {
      'en': 'Edit',
      'ar': 'يحرر',
      'de': 'Bearbeiten',
      'es': 'Editar',
      'fr': 'Modifier',
      'nl': 'Bewerking',
    },
    '3jvncjh1': {
      'en': 'Delete',
      'ar': 'يمسح',
      'de': 'Löschen',
      'es': 'Borrar',
      'fr': 'Supprimer',
      'nl': 'Verwijderen',
    },
  },
  // ModalEditShipperProfile
  {
    'sfgsxbzb': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'nl': 'Bewerk profiel',
    },
    'ttawfajq': {
      'en': 'Below are your profile details',
      'ar': 'فيما يلي تفاصيل ملفك الشخصي',
      'de': 'Nachfolgend finden Sie Ihre Profildetails',
      'es': 'A continuación se muestran los detalles de su perfil.',
      'fr': 'Ci-dessous les détails de votre profil',
      'nl': 'Hieronder staan ​​uw profielgegevens',
    },
    '7jyvyjcx': {
      'en': 'Change Photo',
      'ar': 'غير الصوره',
      'de': 'Foto ändern',
      'es': 'Cambiar foto',
      'fr': 'Changer la photo',
      'nl': 'Verander foto',
    },
    '8q776sf4': {
      'en': 'First Name',
      'ar': 'الاسم الأول',
      'de': 'Vorname',
      'es': 'Nombre de pila',
      'fr': 'Prénom',
      'nl': 'Voornaam',
    },
    'zm3nc87h': {
      'en': 'Last Name',
      'ar': 'اسم العائلة',
      'de': 'Familienname, Nachname',
      'es': 'Apellido',
      'fr': 'Nom de famille',
      'nl': 'Achternaam',
    },
    '81air7qc': {
      'en': 'User_name',
      'ar': 'اسم المستخدم',
      'de': 'Nutzername',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'nl': 'Gebruikersnaam',
    },
    'pirc0qb2': {
      'en': 'Male',
      'ar': 'ذكر',
      'de': 'Männlich',
      'es': 'Masculino',
      'fr': 'Mâle',
      'nl': 'Mannelijk',
    },
    'w8txue3j': {
      'en': 'Female',
      'ar': 'أنثى',
      'de': 'Weiblich',
      'es': 'Femenino',
      'fr': 'Femelle',
      'nl': 'Vrouwelijk',
    },
    '19ooejcp': {
      'en': 'Gender...',
      'ar': 'جنس...',
      'de': 'Geschlecht...',
      'es': 'Género...',
      'fr': 'Genre...',
      'nl': 'Geslacht...',
    },
    '3oqj7rhb': {
      'en': 'Search for an item...',
      'ar': 'البحث عن عنصر...',
      'de': 'Nach einem Artikel suchen...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'nl': 'Zoek een artikel...',
    },
    '63inxtik': {
      'en': 'Bio...',
      'ar': 'السيرة الذاتية...',
      'de': 'Bio...',
      'es': 'Biografía...',
      'fr': 'Biographie...',
      'nl': 'Bio...',
    },
    '6zy983kc': {
      'en': 'Your email is',
      'ar': 'البريد الإلكتروني الخاص بك هو',
      'de': 'Ihre E-Mail lautet',
      'es': 'Tu correo electrónico es',
      'fr': 'Votre email est',
      'nl': 'Je e-mailadres is',
    },
    '87xlecgr': {
      'en': 'Created On:',
      'ar': 'تم إنشاؤها على:',
      'de': 'Erstellt am:',
      'es': 'Creado en:',
      'fr': 'Créé sur:',
      'nl': 'Gemaakt op:',
    },
    '62ztskib': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'nl': 'Annuleren',
    },
    'cpmxopyh': {
      'en': 'Save Changes',
      'ar': 'حفظ التغييرات',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'nl': 'Wijzigingen opslaan',
    },
  },
  // ConfirmEmailVerification
  {
    '7wsa819w': {
      'en': 'Your Email verification',
      'ar': 'التحقق من البريد الإلكتروني الخاص بك',
      'de': 'Ihre E-Mail-Bestätigung',
      'es': 'Tu verificación de correo electrónico',
      'fr': 'Vérification de votre e-mail',
      'nl': 'Uw e-mailverificatie',
    },
    'ou7djv6k': {
      'en':
          'Kindly confirm your email address by clicking on the link that has been sent to you via email in order to proceed further. If you haven\'t received it, please click on the \'Resend\' button below.',
      'ar':
          'يرجى تأكيد عنوان بريدك الإلكتروني من خلال النقر على الرابط الذي تم إرساله إليك عبر البريد الإلكتروني من أجل المضي قدمًا. إذا لم تستلمها، يرجى النقر على زر \"إعادة الإرسال\" أدناه.',
      'de':
          'Bitte bestätigen Sie Ihre E-Mail-Adresse, indem Sie auf den Link klicken, der Ihnen per E-Mail zugesandt wurde, um fortzufahren. Wenn Sie es nicht erhalten haben, klicken Sie bitte unten auf die Schaltfläche „Erneut senden“.',
      'es':
          'Por favor confirme su dirección de correo electrónico haciendo clic en el enlace que se le envió por correo electrónico para continuar. Si no lo ha recibido, haga clic en el botón \'Reenviar\' a continuación.',
      'fr':
          'Veuillez confirmer votre adresse e-mail en cliquant sur le lien qui vous a été envoyé par e-mail afin de continuer. Si vous ne l\'avez pas reçu, veuillez cliquer sur le bouton « Renvoyer » ci-dessous.',
      'nl':
          'Bevestig uw e-mailadres door op de link te klikken die u per e-mail heeft ontvangen om verder te gaan. Als u deze niet heeft ontvangen, klik dan hieronder op de knop \'Opnieuw verzenden\'.',
    },
    'r37hg4dy': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'nl': 'Annuleren',
    },
    'goxttlaa': {
      'en': 'Resend link',
      'ar': 'إعادة إرسال الرابط',
      'de': 'Link erneut senden',
      'es': 'Reenviar enlace',
      'fr': 'Renvoyer le lien',
      'nl': 'Link opnieuw verzenden',
    },
  },
  // DriverPhoneNumberConfirmation
  {
    'gdmwfcpc': {
      'en': 'Enter the confirmation PIN below',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '3rkuz2p8': {
      'en':
          'Please confirm your phone number with the code you have recieved or you will  recieve in a few seconds.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'qcs2kv6x': {
      'en': 'Cancel',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '15cbrnx3': {
      'en': 'Verify Code',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
  },
  // ProfileverifyingButtonSheet
  {
    'ylpffpt5': {
      'en': 'We are currently verifying your account',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'u848tbs9': {
      'en':
          'Please allow us some time to complete the verification process. We will notify you by email once it is finished.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'ck6r8fc7': {
      'en': 'Log Out',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
  },
  // Miscellaneous
  {
    '9yvfoqjc': {
      'en':
          'In order to search nearby, this app requires access to your current location.',
      'ar':
          'من أجل البحث في مكان قريب، يتطلب هذا التطبيق الوصول إلى موقعك الحالي.',
      'de':
          'Um in der Nähe suchen zu können, benötigt diese App Zugriff auf Ihren aktuellen Standort.',
      'es':
          'Para buscar cerca, esta aplicación requiere acceso a su ubicación actual.',
      'fr':
          'Afin d\'effectuer une recherche à proximité, cette application nécessite l\'accès à votre position actuelle.',
      'nl':
          'Om in de buurt te kunnen zoeken, heeft deze app toegang tot uw huidige locatie nodig.',
    },
    '60hxsqsu': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '778ow57c': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'oi8kd7l0': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'ou5v5w54': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'slbv8e2e': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'ukjopcs0': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'go03zds2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'f4x7sdev': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'hq4zrsch': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'gthqab2p': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'lm00s69f': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '4vgz8rf1': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'sfzo2z2e': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'skvy5j7e': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'l12lkcl4': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '2cqn58cj': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'qnngr4b6': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'l14c9x11': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'mwqx0msk': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'qz3edzlt': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'du713021': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'fnot38h8': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '4jwb5g7a': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'f5madsoj': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    '5mhdmue5': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'icqmw67x': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
    'bepkb4yr': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'nl': '',
    },
  },
].reduce((a, b) => a..addAll(b));
